trustin - next
karthik1704/trustin-next pull request #11
Opened 2024-02-29 05:39 UTC by samayapalanikumar

please review trf /success/ page.tsx

2024-02-29 07:21 UTC, karthik1704 requested changes

2024-02-29 07:21 UTC, karthik1704 commented on app/image/1.svg
remove this image

2024-02-29 07:21 UTC, karthik1704 commented on app/image/2.svg
remove this image

2024-02-29 07:21 UTC, karthik1704 commented on app/image/user-05.png
remove this

2024-02-29 07:21 UTC, karthik1704 commented on app/test/page.tsx
remove test folder

2024-03-02 05:18 UTC, karthik1704 commented
do you removed images ?

2024-03-02 05:28 UTC, samayapalanikumar commented
Hi karthi,
sry karthi, i don't delete the images,i forget..

On Sat, Mar 2, 2024 at 10:49 AM Karthik A ***@***.***> wrote:

> do you removed images ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/karthik1704/trustin-next/pull/11#issuecomment-1974307994>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BGARJV6NF7TAXEW6KQCCM6LYWFOMRAVCNFSM6AAAAABD7JJIBKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNZUGMYDOOJZGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-03-02 08:12 UTC, karthik1704 approved these changes
looks good

2024-03-02 08:12 UTC, merged