change error image and not-found
karthik1704/trustin-next pull request #25
Opened 2024-04-13 10:54 UTC by GITHIYON49

2024-04-13 16:05 UTC, karthik1704 requested changes

2024-04-13 16:05 UTC, karthik1704 commented on app/dashboard/trf/[id]/page.tsx
> +  const res2 = await fetch(`${SERVER_API_URL}/products1/trf`, {
please remove 1 from products

2024-04-15 06:28 UTC, GITHIYON49 commented on app/dashboard/trf/[id]/page.tsx
> +  const res2 = await fetch(`${SERVER_API_URL}/products1/trf`, {
removed

2024-04-15 06:30 UTC, GITHIYON49 commented
change image and removed 1 bro pls check and reply

2024-04-15 07:46 UTC, karthik1704 approved these changes

2024-04-15 07:46 UTC, merged