add form
karthik1704/trustin-next pull request #9
Opened 2024-02-17 11:57 UTC by GITHIYON49

create new registartion form

2024-02-17 12:09 UTC, karthik1704 requested changes

2024-02-17 12:09 UTC, karthik1704 commented on app/(auth)/signin/page.tsx
> +                jenish
replace jenish to this " Lorem ipsum dolor sit amet, consectetur adipiscing elit suspendisse."

2024-02-17 12:09 UTC, karthik1704 commented on app/dashboard/registrations/new/page.tsx
> +                      name="test-type"
test_type not test-type and change all name contains - to _

2024-02-17 12:09 UTC, karthik1704 commented on app/dashboard/registrations/new/page.tsx
> +                      name="batch-lot--no"
double dash?

2024-02-17 12:09 UTC, karthik1704 commented on app/dashboard/registrations/new/page.tsx
> +                      placeholder="Enter Date Of Registration"
full name date_of_registration

2024-02-17 12:09 UTC, karthik1704 commented on app/dashboard/registrations/new/page.tsx
> +                      name="date-of-rec"
full name date_of_recived

2024-02-17 12:24 UTC, GITHIYON49 commented on app/dashboard/registrations/new/page.tsx
> +                      name="date-of-rec"
kk bro

2024-02-20 14:47 UTC, karthik1704 approved these changes

2024-02-20 14:48 UTC, merged

2024-02-20 14:48 UTC, karthik1704 commented
Good Work!.